export default Object.freeze({
    TOP_LEFT: 'TOP_LEFT',
    TOP_CENTER: 'TOP_CENTER',
    TOP_RIGHT: 'TOP_RIGHT',
    MIDDLE_LEFT: 'MIDDLE_LEFT',
    MIDDLE_CENTER: 'MIDDLE_CENTER',
    MIDDLE_RIGHT: 'MIDDLE_RIGHT',
    BOTTOM_LEFT: 'BOTTOM_LEFT',
    BOTTOM_CENTER: 'BOTTOM_CENTER',
    BOTTOM_RIGHT: 'BOTTOM_RIGHT'
})